Repository leonardosibela/smart-habits, pull requests merged in 2023-04, with the labels that each got.

#30 Add other languages
  .github/workflows/android.yml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/test/java/com/hikarisource/smarthabits/util/TestData.kt
Labels: FEATURES

#31 Feature/crashlytics
  .github/workflows/android.yml
  .gitignore
  app/build.gradle
  build.gradle
Labels: INFRA

#32 solving a bug when add a habit, that the field show an empty error, n…
  app/src/main/java/com/hikarisource/smarthabits/presentation/features/settings/view/fragment/AddPeriodicHabitFragment.kt
  app/src/main/java/com/hikarisource/smarthabits/presentation/features/settings/view/fragment/EditHabitFragment.kt
  app/src/main/java/com/hikarisource/smarthabits/presentation/features/settings/viewmodel/AddPeriodicHabitViewModel.kt
  app/src/main/java/com/hikarisource/smarthabits/presentation/features/settings/viewmodel/ButtonState.kt
  app/src/main/java/com/hikarisource/smarthabits/presentation/features/settings/viewmodel/EditHabitViewModel.kt
  app/src/test/java/com/hikarisource/smarthabits/presentation/viewmodel/AddPeriodicHabitViewModelTest.kt
  app/src/test/java/com/hikarisource/smarthabits/presentation/viewmodel/EditHabitViewModelTest.kt
Labels: BUG
